<a href="https://colab.research.google.com/github/exponentialR/DeepLearningFundamentals/blob/main/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:

import tensorflow as tf 

In [66]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model 
from tensorflow.keras.optimizers import SGD, Adam 

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


In [67]:
# make the data 

N = 1 
T = 10 
D = 3 
K = 2 
X = np.random.randn(N, T, D)

In [68]:
#Make an RNN
M = 5 
shape = (T, D)
i = Input(shape =(T, D))
x = SimpleRNN(M) (i)
x = Dense(K) (x)

model = Model(i, x)

In [69]:
# make a prediction 
Yhat = model.predict (X)
print(Yhat)

[[-0.6892305  0.9529061]]


In [70]:
#Do a model summary

model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [71]:
model.layers[1].get_weights()

[array([[-0.09467649, -0.10452831,  0.8230737 ,  0.24295396, -0.677675  ],
        [ 0.57254106, -0.56046486,  0.74381155, -0.18048608, -0.19110334],
        [ 0.8658311 ,  0.16680497, -0.04569471, -0.6845612 , -0.86074144]],
       dtype=float32),
 array([[ 0.12173939,  0.0424948 , -0.2524094 ,  0.1749855 , -0.94289094],
        [ 0.05478865, -0.2233293 , -0.28866148,  0.89765096,  0.24087244],
        [ 0.35127   ,  0.8638995 , -0.31162477,  0.04598895,  0.17624417],
        [-0.641198  , -0.00666446, -0.73229253, -0.21748556,  0.07258369],
        [-0.6690682 ,  0.44939002,  0.46861663,  0.337917  , -0.1288674 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [72]:
#check their shapes 
#They should make sense 
#The first output is input and it is hideen 
#The second output is hidden of hidden 
#The third output is bias term (vector of length M)

a,b,c = model.layers[1].get_weights()
print (a.shape, b.shape, c.shape)


(3, 5) (5, 5) (5,)


In [73]:
#Assign weight variables 
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()


In [74]:
#Do manual RNN calculation 
h_last = np.zeros(M)
x = X[0]
Yhats = []

for t in range (T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh))
  y = h.dot(Wo)+bo
  Yhats.append(y)

  h_last = h 

print (Yhats[-1])

[-0.68923051  0.95290602]
